language: node_js
node_js:
- "stable"
cache:
    directories:
    - node_modules
script:
    - yarn test
    - yarn build
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: build
          on:
            branch: master
